"""Add audit fields

Revision ID: 9dfded2c269a
Revises: d5bc8aa105e8
Create Date: 2026-07-09 16:40:30.179939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dfded2c269a'
down_revision = 'd5bc8aa105e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
