"""Add updated_at to category and status

Revision ID: c1abd7dafa08
Revises: 9dfded2c269a
Create Date: 2026-07-09 16:49:50.800691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1abd7dafa08'
down_revision = '9dfded2c269a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
